### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by akoivu** [nullkaaryle/Tsoha-Reseptiarkisto#1]
# Koodikatselmointi

## Latauksen ajankohta
Torstai 24.8. klo 14:30

### Kontrollerit ja mallit

Koodi oli hyvin selkeää ja helppolukuista. Muuttujanimet olivat kuvaavia. Toisaalta, koska suuri osa muuttujanimistä oli suomeksi, oli päätös nimetä osa muuttujista englannin kielellä mielestäni jännä. Toisaalta ymmärrän, että nämä muuttujat, esimerkiksi `$params` ovat hyvin vakiintuneita nimeämiseltään. 

Toinenkin pointti saattaa olla vain makuasia, mutta yleensä sulkuja ennen ja niiden jälkeen on väli, kun kyseessä on ehtolause, metodi tai muu vastaava. Esimerkiksi pätkän 
``` 
if(!$apteekki){
    View::make('kirjautuminen.html', array('message' => 'Väärä käyttäjätunnus tai salasana!', 'kayttajatunnus' => $params['kayttajatunnus']));
}else{
    $_SESSION['apteekki'] = $apteekki->id;
    Redirect::to('/reseptit', array('message' => 'Tervetuloa ' . $apteekki->nimi . '!'));
}
```
myös esimerkiksi NetBeans formatoi seuraavasti
``` 
if (!$apteekki) {
    View::make('kirjautuminen.html', array('message' => 'Väärä käyttäjätunnus tai salasana!', 'kayttajatunnus' => $params['kayttajatunnus']));
} else {
    $_SESSION['apteekki'] = $apteekki->id;
    Redirect::to('/reseptit', array('message' => 'Tervetuloa ' . $apteekki->nimi . '!'));
}
```
Tässä häiritsi eniten se, että eri kohdissa koodia käytäntö oli erilainen.
Yleisesti koodia oli kuitenkin miellyttävä lukea.

### Näkymät

Näkymissä minua hämmensi vaihtelevat sisennykset. Välillä sisennykset olivat kahden välilyönnin, ja välillä neljän välilyönnin mittaisia. Lisäksi välillä blokin avaus- ja lopetustagit olivat eri tasalla. Tämä voi johtua myös siitä, että ennenkin NetBeansini on jostakin syystä sekoittanut toisen henkilön projekteja avatessa sisennykset aivan täysin. Kumminkin yhtenä esimerkkinä:
```
<p>
    <a href="{{base_path}}/ainesosat" 
      button type="button" 
      class="btn btn-primary btn-xs">Palaa ainesosalistaukseen</button></a>
  </p>
```

Lisäksi ainakin `laake.html`:stä puuttuu aivan lopusta blokista
```
<!-- Painikkeet tähän --> 
 <!-- Painikkeet tähän --> 
        <td><button type="button" class="btn btn-warning" href="#">Muokkaa</button></td>
        <td><button type="button" class="btn btn-danger" href="#">Poista</button></td>
      </tr>
```
aloitustagi `<tr>`.

**Comment by nullkaaryle** [comment]
Kiitos katselmoinnista!

Olen arponut viimeisimpien palautusten jälkeen, muuttaisinko koko koodin englanniksi, koska osittainen suomen kieli tuntuu itsestäkin välillä sekavalta. Teen ehkä muutoksen lopulliseen palautukseen.

Ja huomasin myös itsekin, että sisennykset alkavat karata käsistä, joten kyse ei ole sinun NetBeansistäsi, vaan minun huolimattomuudestani. Voisin lisätä Sublime Textiin jonkin format-apupaketin html:lle ja php:lle, varmaan sellaisiakin löytyy!

Hyvä, että kommentoit näistä samoista jutuista mitä itsekin olin ajatellut, niin tuli vahvistus omille epäilyille. :D
